version: "3"

services:
  watch_tower_server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ./target/release/watch-tower
    ports:
      - 8000:8000
    volumes:
      - ./db_saves:/app/db_saves
