version: "3"

services:
  watch_tower_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./target/release/watch-tower
    ports:
      - 8000:8000
    volumes:
      - ./db_saves:/app/db_saves
      - ./config.json:/app/config.json
    deploy:
      resources:
        limits:
          memory: 4g  # increase limit to 4GB

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.watchtower.starknet.id"
      SITES: "api.watchtower.starknet.id=watch_tower_server:8000"
    deploy:
      resources:
        limits:
          memory: 1g  # increase limit to 1GB

volumes:
  ssl_data:
