version: "3"

services:
  watch_tower_server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ./target/release/watch-tower
    ports:
      - 8000:8000

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.watchtower.starknet.id"
      SITES: "api.watchtower.starknet.id=watch_tower_server:8000"

volumes:
  ssl_data: